branches:
  only:
    - master
    - develop

skip_tags: true
skip_branch_with_pr: true
skip_commits:
  message: /\[(skip ci|ci skip)\]/

version: 1.8.0.{build}
image: Visual Studio 2022

install:
  - choco install codecov -y

nuget:
  disable_publish_on_pr: true

environment:
  SonarCloudAccessToken:
    secure: hZ+EdDQLy/K+ngEIPrw7DM//Lft9RldmiOoGNhNz8m9iyfJ3ZJhylBm0FduR6fWT
  GitHubAccessToken:
    secure: 03TOIdkL4AV7WgYpsFpMzzamDxMjvs4qtox1v+DBL5jqG3vZTht65qHSWMwNPIq8

build_script:
  - set JAVA_HOME=C:\Program Files\Java\jdk11
  - set PATH=%JAVA_HOME%\bin;%PATH%
  - dotnet tool install --global dotnet-sonarscanner
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER) { dotnet sonarscanner begin /n:Softlr.Suppress /k:softlr.suppress /v:1.8 /d:sonar.host.url=https://sonarcloud.io /o:rayell-github /d:sonar.login=$env:SonarCloudAccessToken /d:sonar.github.pullRequest=$env:APPVEYOR_PULL_REQUEST_NUMBER /d:sonar.github.repository=Softlr/Suppress /d:sonar.github.oauth=$env:GitHubAccessToken /d:sonar.cs.opencover.reportsPaths=coverage.xml }
  - ps: if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { dotnet sonarscanner begin /n:Softlr.Suppress /k:softlr.suppress /v:1.8 /d:sonar.host.url=https://sonarcloud.io /o:rayell-github /d:sonar.login=$env:SonarCloudAccessToken /d:sonar.cs.opencover.reportsPaths=coverage.xml }
  - dotnet build -c Release

after_build:
  - ps: dotnet pack -c Release --no-build -o $env:APPVEYOR_BUILD_FOLDER -p:Version=1.8.0 -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg

test_script:
  - dotnet test -c Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=../../coverage.xml
  - ps: mv ./coverage.net5.0.xml ./coverage.xml
  - ps: dotnet sonarscanner end /d:sonar.login=$env:SonarCloudAccessToken

after_test:
  - codecov -f coverage.xml

artifacts:
  - path: coverage.xml
  - path: ./*.nupkg
  - path: ./*.snupkg

deploy:
  - provider: GitHub
    on:
      branch: master
    release: 1.8.0
    artifact: /.*\.nupkg/
    auth_token:
      secure: 03TOIdkL4AV7WgYpsFpMzzamDxMjvs4qtox1v+DBL5jqG3vZTht65qHSWMwNPIq8
  - provider: NuGet
    on:
      branch: master
    artifact: /.*(\.|\.s)nupkg/
    api_key:
      secure: RoNu0KbJqWNledqfHkctON53FTzzgNGVj7U6bpzwrC1MlEr5INEsP7FyEpEZBX1D