name: "Release"

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+(-preview[0-9][0-9][0-9])?"
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    #- name: Verify commit exists in origin/main
    #  run: |
    #    git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    #    git branch --remote --contains | grep origin/main
    
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
      
    - name: Restore
      run: dotnet restore
    
    - name: Build
      run: dotnet build -c Release /p:Version=${VERSION} --no-restore
    
    - name: Test
      run: dotnet test -c Release /p:Version=${VERSION} --no-restore  
    
    - name: Pack
      run: dotnet pack -c Release /p:Version=${VERSION} --no-build --output .
    
    - name: Push
      run: dotnet nuget push Softlr.Suppress.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
